name: Lint & Deploy

on:
  pull_request:
  push:
    branches: [ main ]

env:
  GCP_PROJECT: consensus-engine
  REGION: europe-west1
  AR_HOST: europe-west1-docker.pkg.dev
  REPO: consensusengine-repo
  WEB_SERVICE: consensusengine
  MIGRATE_JOB: db-migrate

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint  # e.g. "eslint . --ext .ts,.tsx --max-warnings=0"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.AR_HOST }} --quiet

      - name: Build & push image
        env:
          NODE_ENV: production
          MONGODB_URI: "mongodb://dummyvalue:blabla@mongodb.net/consensusengine"
        run: |
          WEB_IMG=${{ env.AR_HOST }}/${{ env.GCP_PROJECT }}/${{ env.REPO }}/web:${{ github.sha }}
          docker build -t "$WEB_IMG" .
          docker push "$WEB_IMG"
          echo "WEB_IMG=$WEB_IMG" >> $GITHUB_ENV

      - name: Deploy Next.js service
        run: |
          gcloud run deploy "${{ env.WEB_SERVICE }}" \
            --image "${{ env.WEB_IMG }}" \
            --region "${{ env.REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production,REACT_APP_BASE_URL="https://ce.dukedan.uk",NODE_OPTIONS="--dns-result-order=ipv4first" \
            --set-secrets=MONGODB_URI=DATABASE_URL:latest,AUTH_SECRET=AUTH_SECRET:latest,AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING=AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING:latest
