name: Lint (Feature Branches)

on:
  pull_request:
    branches-ignore: [ main ]
  push:
    branches-ignore: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: ESLint
        run: npm run lint
        # e.g. package.json -> "lint": "eslint . --ext .ts,.tsx --max-warnings=0"
